contract:
  deployed_config_path:
    default: shared/config/data/contract/deployed.yaml
    chain:
      ganache: &ganache tmp/deployed_ganache.yaml
config:
  added:
    - shared/config/data/contract/deployed.yaml
    - *ganache
    - shared/config/data/contract/abi.yaml
    - shared/config/data/chain.yaml
    - local.yaml
